#ifndef RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_
#define RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_

#include "ICFeature.h"
#include <deque>

namespace nprs {

}

#endif // RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_
