#ifndef RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_H
#define RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_H

#include "ICFeature.h"
#include <deque>

namespace nprs {



}

#endif // RECSYSTEM_ERHORIZONTALCROSSINGSFEATURE_H
