FUNCTION(CHECK_FILES source_files)
	FOREACH(file ${source_files})
		MESSAGE(${file})
		IF(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${file})
			MESSAGE("${file} not exists")
			FILE(APPEND ${CMAKE_CURRENT_SOURCE_DIR}/${file} "\n")
		ENDIF()
	ENDFOREACH()
ENDFUNCTION()

FUNCTION(GROUP_FILES directories)
	FOREACH(directory ${directories})
		FILE(GLOB dir_headers "${directory}/*.h")
		FILE(GLOB dir_sources "${directory}/*.cpp")
		FILE(GLOB dir_ui "${directory}/*.ui")
		FILE(GLOB dir_inl "${directory}/*.inl")
		STRING(REGEX REPLACE "/" "\\\\\\\\" convdir ${directory})
		SOURCE_GROUP(${convdir} FILES ${dir_headers} ${dir_sources} ${dir_ui} ${dir_inl})
	ENDFOREACH()
ENDFUNCTION()
