/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nprs_app_recognition_jni_NativeRecognizer */

#ifndef _Included_com_nprs_app_recognition_jni_NativeRecognizer
#define _Included_com_nprs_app_recognition_jni_NativeRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nprs_app_recognition_jni_NativeRecognizer
 * Method:    recognizeNative
 * Signature: ([III)Lcom/nprs/app/recognition/common_structures/RecognitionResults;
 */
JNIEXPORT jobject JNICALL Java_com_nprs_app_recognition_jni_NativeRecognizer_recognizeNative
        (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
